using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using ConsoleApp;

namespace ConsoleApp.Tests
{
    [TestClass]
    public class Context6Tests
    {
        [TestMethod]
        public void ATest()
        {
            Assert.Fail("autogenerated");
        }
    }
}