using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using ConsoleApp;

namespace ConsoleApp.Tests
{
    [TestClass]
    public class SimpleClassTests
    {
        [TestMethod]
        public void VoidMethodTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void PublicMethodTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}